- name: 'configure storage'
  hosts: storage
  become: true
  tasks:
    - name: 'install storage utilities'
      ansible.builtin.apt:
        name:
          - 'hdparm'
          - 'smartmontools'

    - name: 'install longhorn dependencies'
      ansible.builtin.apt:
        name:
          - 'open-iscsi'

    - name: 'create /dev/sda1 partition'
      community.general.parted:
        device: '/dev/sda'
        number: 1
        state: present
        fs_type: ext4

    - name: 'create ext4 fs on /dev/sda1'
      community.general.filesystem:
        dev: '/dev/sda1'
        fstype: ext4

    - name: 'mount /dev/sda1 to /var/lib/longhorn'
      ansible.posix.mount:
        path: '/var/lib/longhorn'
        src: '/dev/sda1'
        fstype: ext4
        opts: 'defaults,noatime'
        state: mounted

    - name: 'label storage nodes to be used with longhorn'
      become: false
      delegate_to: localhost
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Node
          metadata:
            name: "{{ inventory_hostname_short }}"
            labels:
              node.longhorn.io/create-default-disk: 'true'

- name: 'install longhorn'
  hosts: localhost
  tasks:
    - name: 'add longhorn helm repo'
      kubernetes.core.helm_repository:
        name: 'longhorn'
        repo_url: 'https://charts.longhorn.io'

    - name: 'install longhorn'
      kubernetes.core.helm:
        name: 'longhorn'
        chart_ref: 'longhorn/longhorn'
        release_namespace: 'longhorn-system'
        create_namespace: true
        values_files:
          - 'values.yaml'

    # https://kubernetes.io/docs/concepts/storage/storage-classes/#default-storageclass
    - name: 'unset local-path storage class as default'
      kubernetes.core.k8s:
        state: patched
        definition:
          apiVersion: v1
          kind: StorageClass
          metadata:
            name: 'local-path'
            annotations:
              storageclass.kubernetes.io/is-default-class: 'false'
