- name: 'configure packages'
  hosts: all
  become: true
  tasks:
    - name: 'apt-get update'
      ansible.builtin.apt:
        update_cache: true

    - name: 'apt-get dist-upgrade'
      ansible.builtin.apt:
        upgrade: 'dist'

    - name: 'apt-get upgrade'
      ansible.builtin.apt:
        name: '*'
        state: latest

    - name: 'apt-get autoremove --purge'
      ansible.builtin.apt:
        autoremove: true
        purge: true

    # force changed=false because ansible always returns true here
    # https://github.com/ansible/ansible/blob/f6be5ab2241377b93d5fc06c87d6bf86c4225123/lib/ansible/modules/apt.py#L1351
    - name: 'apt-get clean'
      ansible.builtin.apt:
        clean: true
      changed_when: false

    - name: 'install useful utilities'
      ansible.builtin.apt:
        name:
          - 'git'
          - 'vim'
          - 'tree'
          - 'tmux'
          - 'jq'
          - 'ripgrep'
          - 'htop'
          - 'strace'
          - 'lsof'
          - 'ldnsutils'
          - 'arping'
          - 'tcpdump'
          - 'iperf3'

    - name: 'choose vim as editor'
      community.general.alternatives:
        name: 'editor'
        path: '/usr/bin/vim.basic'
